Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.name = "styleconnect-tomcat"
    end
    config.vm.network "forwarded_port", guest: 8080, host: 80
end