Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.name = "styleconnect-jenkins"
    end
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    config.vm.synced_folder "/jars", "/jars", create: true, mount_options["uid=1000"]
end