Vagrant.configure("2") do |config|
    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.name = "styleconnect-mysql"
    end
    config.vm.network "private_network", ip: "192.168.1.101"
end